# Generated by Django 5.2.18 on 2026-10-08 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("members", "0033_memberlist_organization_wide"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Ausstehend"), ("confirmed", "Bestätigt"), ("rejected", "Abgelehnt")],
                        default="pending",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True, verbose_name="Verknüpft am")),
                ("confirmed_at", models.DateTimeField(blank=True, null=True, verbose_name="Bestätigt am")),
                ("rejected_at", models.DateTimeField(blank=True, null=True, verbose_name="Abgelehnt am")),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verknüpft von",
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_link",
                        to="members.member",
                        verbose_name="Mitgliedsdatensatz",
                    ),
                ),
                (
                    "parent",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_link",
                        to="members.parent",
                        verbose_name="Elterndatensatz",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_link",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Konto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kontoverknüpfung",
                "verbose_name_plural": "Kontoverknüpfungen",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("parent__isnull", False), ("member__isnull", False), _connector="OR"),
                        name="account_link_has_target",
                    )
                ],
            },
        ),
    ]
