# Generated by Django 5.2.18 on 2026-10-08 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0033_memberlist_organization_wide"),
        ("portal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, verbose_name="E-Mail")),
                ("token_hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_invitations",
                        to="members.member",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_invitations",
                        to="members.parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portaleinladung",
                "verbose_name_plural": "Portaleinladungen",
                "ordering": ["-created_at"],
                "permissions": [("invite_portal_account", "Eltern und Mitglieder ins Portal einladen")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("member__isnull", True), ("parent__isnull", False)),
                            models.Q(("member__isnull", False), ("parent__isnull", True)),
                            _connector="OR",
                        ),
                        name="invitation_has_one_target",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("accepted_at__isnull", True), ("parent__isnull", False), ("revoked_at__isnull", True)
                        ),
                        fields=("parent",),
                        name="one_open_invitation_per_parent",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("accepted_at__isnull", True), ("member__isnull", False), ("revoked_at__isnull", True)
                        ),
                        fields=("member",),
                        name="one_open_invitation_per_member",
                    ),
                ],
            },
        ),
    ]
