# Generated by Django 5.2.18 on 2026-10-08 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0033_memberlist_organization_wide"),
        ("portal", "0002_invitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invitation",
            options={
                "ordering": ["-created_at"],
                "permissions": [("invite_portal_account", "Portalzugänge einladen und verwalten")],
                "verbose_name": "Portaleinladung",
                "verbose_name_plural": "Portaleinladungen",
            },
        ),
        migrations.CreateModel(
            name="ParentAccessExtension",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("until", models.DateField(verbose_name="Elternzugriff bis")),
                ("reason", models.CharField(max_length=500, verbose_name="Begründung")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_access_extensions",
                        to="members.member",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_extensions",
                        to="members.parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verlängerung Elternzugriff",
                "verbose_name_plural": "Verlängerungen Elternzugriff",
                "ordering": ["-until"],
            },
        ),
    ]
