# Generated by Django 5.2.18 on 2026-10-08 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0006_preserve_assignment_sources"),
        ("portal", "0003_access_extension"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "member_portal_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Wie Organisation"),
                            ("off", "Keine Mitgliederkonten"),
                            ("min_age", "Ab Alter"),
                            ("all", "Alle"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("member_portal_min_age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("visibility", models.JSONField(blank=True, default=dict)),
                ("ceiling", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "department",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_policy",
                        to="departments.department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portal-Freigabe",
                "verbose_name_plural": "Portal-Freigaben",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("department__isnull", True)),
                        fields=("department",),
                        name="one_org_portal_policy",
                    )
                ],
            },
        ),
    ]
