# Generated by Django 5.2.18 on 2026-10-08 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0033_memberlist_organization_wide"),
        ("portal", "0004_portal_policy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Offen"),
                            ("partial", "Teilweise übernommen"),
                            ("applied", "Übernommen"),
                            ("rejected", "Abgelehnt"),
                            ("withdrawn", "Zurückgezogen"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("fields", models.JSONField(default=list)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.CharField(blank=True, default="", max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="members.member",
                    ),
                ),
                (
                    "target_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="members.parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Änderungsantrag",
                "verbose_name_plural": "Änderungsanträge",
                "ordering": ["-updated_at"],
                "permissions": [("review_changerequest", "Änderungsanträge aus dem Portal prüfen")],
            },
        ),
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_kind", models.CharField(max_length=10)),
                ("target_id", models.PositiveBigIntegerField()),
                ("field", models.CharField(max_length=30)),
                ("old", models.CharField(blank=True, default="", max_length=300)),
                ("new", models.CharField(blank=True, default="", max_length=300)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("self_change", models.BooleanField(default=False)),
                (
                    "applied_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "change_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="log",
                        to="portal.changerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Änderungsprotokoll",
                "verbose_name_plural": "Änderungsprotokoll",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="changerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("target_member__isnull", False), ("target_parent__isnull", True)),
                    models.Q(("target_member__isnull", True), ("target_parent__isnull", False)),
                    _connector="OR",
                ),
                name="change_request_has_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="changerequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open"), ("target_member__isnull", False)),
                fields=("target_member",),
                name="one_open_change_request_per_member",
            ),
        ),
        migrations.AddConstraint(
            model_name="changerequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open"), ("target_parent__isnull", False)),
                fields=("target_parent",),
                name="one_open_change_request_per_parent",
            ),
        ),
        migrations.AddIndex(
            model_name="changelog",
            index=models.Index(fields=["target_kind", "target_id"], name="portal_chan_target__9764b0_idx"),
        ),
    ]
