# Generated by Django 5.2.18 on 2026-10-08 16:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0006_preserve_assignment_sources"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InboxItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(max_length=30)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("requests", "Anträge"),
                            ("registrations", "Meldungen"),
                            ("staffing", "Besetzung"),
                            ("accounts", "Konten"),
                            ("participation", "Teilnahme"),
                        ],
                        max_length=20,
                    ),
                ),
                ("item_type", models.CharField(choices=[("task", "Aufgabe"), ("notice", "Hinweis")], max_length=10)),
                ("object_type", models.CharField(blank=True, default="", max_length=40)),
                ("object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("link", models.CharField(blank=True, default="", max_length=300)),
                ("permission", models.CharField(blank=True, default="", max_length=100)),
                ("count", models.PositiveIntegerField(default=1)),
                ("group_key", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "task_state",
                    models.CharField(
                        blank=True, choices=[("open", "Offen"), ("done", "Erledigt")], default="", max_length=10
                    ),
                ),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                ("done_via", models.CharField(blank=True, default="", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="departments.department"
                    ),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Eingangseintrag",
                "verbose_name_plural": "Eingangseinträge",
                "ordering": ["-updated_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="InboxRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("hidden_at", models.DateTimeField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="notifications.inboxitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbox_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(max_length=30)),
                ("email", models.BooleanField(default=True)),
                ("push", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="inboxitem",
            index=models.Index(fields=["object_type", "object_id"], name="notificatio_object__2170e3_idx"),
        ),
        migrations.AddConstraint(
            model_name="inboxitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("group_key__isnull", False)), fields=("group_key",), name="unique_inbox_group_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="inboxrecipient",
            constraint=models.UniqueConstraint(fields=("item", "user"), name="unique_inbox_recipient"),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(fields=("user", "kind"), name="unique_notification_preference"),
        ),
    ]
