# Generated by Django 5.2.18 on 2026-10-08 16:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_inbox"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pushsubscription",
            name="participation",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="requests",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="EmailDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_key", models.CharField(max_length=160, unique=True)),
                ("kind", models.CharField(max_length=30)),
                ("context", models.JSONField(default=dict)),
                ("bundle_key", models.CharField(blank=True, db_index=True, default="", max_length=160)),
                ("send_after", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
