# Generated by Django 5.0.14 on 2026-05-03 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("departments", "0003_department_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "provider",
                    models.CharField(
                        choices=[("spond", "Spond"), ("hi_org", "Hi-Org")], max_length=30, verbose_name="Quelle"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("organization", "Organisation"), ("department", "Abteilung")],
                        default="organization",
                        max_length=20,
                        verbose_name="Geltung",
                    ),
                ),
                (
                    "run_mode",
                    models.CharField(
                        choices=[("manual", "Nur manuell"), ("interval", "Intervall")],
                        default="manual",
                        max_length=20,
                        verbose_name="Ausführung",
                    ),
                ),
                (
                    "interval_minutes",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Intervall (Minuten)"),
                ),
                (
                    "deletion_mode",
                    models.CharField(
                        choices=[("review", "Zur Prüfung markieren"), ("auto_delete", "Automatisch löschen")],
                        default="review",
                        max_length=20,
                        verbose_name="Löschmodus",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("config", models.JSONField(blank=True, default=dict, verbose_name="Konfiguration")),
                ("credentials", models.JSONField(blank=True, default=dict, verbose_name="Zugangsdaten")),
                ("last_run_at", models.DateTimeField(blank=True, null=True, verbose_name="Letzte Ausführung")),
                ("next_run_at", models.DateTimeField(blank=True, null=True, verbose_name="Nächste Ausführung")),
                ("last_success_at", models.DateTimeField(blank=True, null=True, verbose_name="Letzter Erfolg")),
                ("last_error", models.TextField(blank=True, verbose_name="Letzter Fehler")),
                ("last_tested_at", models.DateTimeField(blank=True, null=True, verbose_name="Zuletzt getestet")),
                ("last_test_status", models.BooleanField(blank=True, null=True, verbose_name="Letztes Testergebnis")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sync_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_jobs",
                        to="departments.department",
                        verbose_name="Abteilung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Synchronisationsjob",
                "verbose_name_plural": "Synchronisationsjobs",
                "ordering": ["name"],
                "permissions": (
                    ("run_syncjob", "Kann Synchronisationsjobs ausführen"),
                    ("test_syncjob", "Kann Synchronisationsjobs testen"),
                    ("garbage_collect_syncjob", "Kann Synchronisationsbereinigung ausführen"),
                ),
            },
        ),
        migrations.CreateModel(
            name="SyncBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "object_type",
                    models.CharField(
                        choices=[("member", "Mitglied"), ("group", "Gruppe")], max_length=20, verbose_name="Objekttyp"
                    ),
                ),
                ("external_id", models.CharField(max_length=255, verbose_name="Externe ID")),
                ("external_name", models.CharField(blank=True, max_length=255, verbose_name="Externer Name")),
                ("object_id", models.PositiveBigIntegerField(verbose_name="Objekt-ID")),
                ("is_deleted_in_source", models.BooleanField(default=False, verbose_name="In Quelle gelöscht")),
                (
                    "pending_garbage_collection",
                    models.BooleanField(default=False, verbose_name="Zur Bereinigung vorgemerkt"),
                ),
                (
                    "override_local_changes",
                    models.BooleanField(default=False, verbose_name="Lokale Änderungen überschreiben"),
                ),
                ("managed_fields", models.JSONField(blank=True, default=list, verbose_name="Gesteuerte Felder")),
                ("last_seen_at", models.DateTimeField(blank=True, null=True, verbose_name="Zuletzt gesehen")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Inhaltstyp",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bindings",
                        to="external_sync.syncjob",
                        verbose_name="Job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Synchronisationsbindung",
                "verbose_name_plural": "Synchronisationsbindungen",
                "ordering": ["object_type", "external_name", "external_id"],
            },
        ),
        migrations.CreateModel(
            name="SyncRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("running", "Läuft"),
                            ("succeeded", "Erfolgreich"),
                            ("failed", "Fehlgeschlagen"),
                            ("cancelled", "Abgebrochen"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("trigger", models.CharField(default="manual", max_length=30, verbose_name="Auslöser")),
                ("summary", models.JSONField(blank=True, default=dict, verbose_name="Zusammenfassung")),
                ("imported_members", models.PositiveIntegerField(default=0, verbose_name="Importierte Mitglieder")),
                ("imported_groups", models.PositiveIntegerField(default=0, verbose_name="Importierte Gruppen")),
                ("updated_members", models.PositiveIntegerField(default=0, verbose_name="Aktualisierte Mitglieder")),
                ("updated_groups", models.PositiveIntegerField(default=0, verbose_name="Aktualisierte Gruppen")),
                ("flagged_for_review", models.PositiveIntegerField(default=0, verbose_name="Zur Prüfung markiert")),
                ("deleted_objects", models.PositiveIntegerField(default=0, verbose_name="Gelöschte Objekte")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="Gestartet am")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Beendet am")),
                ("error_message", models.TextField(blank=True, verbose_name="Fehlermeldung")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="external_sync.syncjob",
                        verbose_name="Job",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ausgelöst von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Synchronisationslauf",
                "verbose_name_plural": "Synchronisationsläufe",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="syncbinding",
            constraint=models.UniqueConstraint(
                fields=("job", "object_type", "external_id"), name="uniq_sync_binding_ext"
            ),
        ),
        migrations.AddConstraint(
            model_name="syncbinding",
            constraint=models.UniqueConstraint(
                fields=("job", "content_type", "object_id"), name="uniq_sync_binding_object"
            ),
        ),
    ]
