# Generated by Django 5.0.14 on 2025-09-18 19:01

from django.db import migrations


def add_neu_status(apps, schema_editor):
    """Add the 'Neu' status to the order workflow"""
    OrderStatus = apps.get_model('orders', 'OrderStatus')
    
    # Add the new 'Neu' status
    neu_status, created = OrderStatus.objects.get_or_create(
        code='NEW',
        defaults={
            'name': 'Neu',
            'description': 'Neue Bestellung, die noch nicht an den Gerätewart weitergeleitet wurde',
            'color': '#6c757d',  # Gray color
            'is_active': True,
            'sort_order': 0  # First in the workflow
        }
    )
    
    if created:
        # Update sort order for existing statuses to make room for NEW at the beginning
        existing_statuses = OrderStatus.objects.exclude(code='NEW').order_by('sort_order')
        for i, status in enumerate(existing_statuses, start=10):
            status.sort_order = i * 10
            status.save()


def remove_neu_status(apps, schema_editor):
    """Remove the 'Neu' status (reverse operation)"""
    OrderStatus = apps.get_model('orders', 'OrderStatus')
    OrderStatus.objects.filter(code='NEW').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_notificationlog_additional_data'),
    ]

    operations = [
        migrations.RunPython(add_neu_status, remove_neu_status),
    ]
