# Generated by Django 5.0.14 on 2026-05-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_alter_emailtemplate_template_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="layout",
            field=models.CharField(
                choices=[
                    ("none", "Kein Layout (reines HTML)"),
                    ("general", "Allgemeine Information"),
                    ("important", "Wichtige Mitteilung"),
                    ("events", "Veranstaltung / Termin"),
                ],
                default="none",
                help_text="Layout-Vorlage, in die der HTML-Inhalt eingebettet wird.",
                max_length=20,
                verbose_name="Layout",
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("order_created", "Bestellung erstellt"),
                    ("status_update", "Status geändert"),
                    ("bulk_update", "Massenänderung"),
                    ("pending_reminder", "Erinnerung"),
                    ("daily_summary", "Tägliche Zusammenfassung"),
                    ("weekly_report", "Wöchentlicher Bericht"),
                    ("password_reset", "Passwort zurücksetzen"),
                    ("ext_auth_pw_info", "Externer Benutzer – Passworthinweis"),
                    ("order_confirmed", "Bestellung bestätigt (Legacy)"),
                    ("order_shipped", "Bestellung versandt (Legacy)"),
                    ("order_cancelled", "Bestellung storniert (Legacy)"),
                    ("order_summary", "Bestellübersicht (Legacy)"),
                ],
                max_length=20,
                unique=True,
                verbose_name="Typ",
            ),
        ),
    ]
