# Generated by Django 5.0.14 on 2026-05-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_add_layout_to_emailtemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLayoutTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "layout_type",
                    models.CharField(
                        choices=[
                            ("general", "Allgemeine Information"),
                            ("important", "Wichtige Mitteilung"),
                            ("events", "Veranstaltung / Termin"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Layout-Typ",
                    ),
                ),
                ("html_content", models.TextField(verbose_name="HTML-Inhalt")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "E-Mail-Layout-Vorlage",
                "verbose_name_plural": "E-Mail-Layout-Vorlagen",
            },
        ),
    ]
