# Generated by Django 5.0.14 on 2026-09-19 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_item_is_standard_item'),
        ('orders', '0012_sync_orderable_items_from_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='receipt_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_order_item', to='inventory.transaction', verbose_name='Lagerzugang'),
        ),
    ]
