# Generated by Django 5.2.18 on 2026-10-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0016_alter_order_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("order_created", "Bestellung erstellt"),
                    ("status_update", "Status geändert"),
                    ("bulk_update", "Massenänderung"),
                    ("pending_reminder", "Erinnerung"),
                    ("daily_summary", "Tägliche Zusammenfassung"),
                    ("weekly_report", "Wöchentlicher Bericht"),
                    ("password_reset", "Passwort zurücksetzen"),
                    ("ext_auth_pw_info", "Externer Benutzer – Passworthinweis"),
                    ("portal_invite", "Portal: Einladung"),
                    ("account_link", "Konto: Verknüpfung bestätigen"),
                    ("cr_submitted", "Änderungsantrag gestellt"),
                    ("cr_decided", "Änderungsantrag entschieden"),
                    ("reg_cancelled", "Kurzfristige Abmeldung"),
                    ("reg_digest", "Meldungen: Tageszusammenfassung"),
                    ("slot_free_manual", "Platz frei (Warteliste manuell)"),
                    ("staffing_at_risk", "Mindestbesetzung gefährdet"),
                    ("waitlist_placed", "Teilnahme: Warteliste"),
                    ("waitlist_promoted", "Teilnahme: Nachgerückt"),
                    ("assign_published", "Teilnahme: Zuteilung"),
                    ("session_changed", "Teilnahme: Dienst geändert oder abgesagt"),
                    ("session_published", "Teilnahme: Neuer Dienst"),
                    ("eligibility_conflict", "Voraussetzung nicht mehr erfüllt"),
                    ("parent_access_end", "Elternzugriff endet"),
                    ("order_confirmed", "Bestellung bestätigt (Legacy)"),
                    ("order_shipped", "Bestellung versandt (Legacy)"),
                    ("order_cancelled", "Bestellung storniert (Legacy)"),
                    ("order_summary", "Bestellübersicht (Legacy)"),
                ],
                max_length=20,
                unique=True,
                verbose_name="Typ",
            ),
        ),
    ]
