# Generated by Django 5.0.11 on 2025-06-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicebook', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
