# Generated by Django 5.0.14 on 2026-05-01 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "code",
                    models.SlugField(
                        help_text="Eindeutiges Kürzel für die Abteilung (wird automatisch aus dem Namen generiert)",
                        unique=True,
                        verbose_name="Kürzel",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Beschreibung")),
                ("address", models.CharField(blank=True, max_length=300, verbose_name="Adresse")),
                ("phone", models.CharField(blank=True, max_length=50, verbose_name="Telefon")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am")),
            ],
            options={
                "verbose_name": "Abteilung",
                "verbose_name_plural": "Abteilungen",
                "ordering": ["name"],
                "permissions": (
                    ("can_access_all_departments", "Kann alle Abteilungen sehen"),
                    ("can_manage_all_departments", "Kann alle Abteilungen verwalten"),
                ),
            },
        ),
        migrations.CreateModel(
            name="UserDepartmentRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("manager", "Verwalter"), ("viewer", "Betrachter")],
                        default="viewer",
                        max_length=20,
                        verbose_name="Rolle",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="departments.department",
                        verbose_name="Abteilung",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benutzer-Abteilung-Zuordnung",
                "verbose_name_plural": "Benutzer-Abteilung-Zuordnungen",
                "unique_together": {("user", "department")},
            },
        ),
    ]
