# Generated by Django 5.0.14 on 2026-10-04 16:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("departments", "0003_department_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.SlugField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z][a-z0-9_]*$", "Nur Kleinbuchstaben, Ziffern und Unterstriche erlaubt."
                            )
                        ],
                        verbose_name="Stabiler Vorlagenschlüssel",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Anzeigename")),
                ("description", models.TextField(blank=True, verbose_name="Beschreibung")),
                ("template_version", models.PositiveIntegerField(default=1, verbose_name="Vorlagenversion")),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("organization", "Organisation"),
                            ("department", "Abteilung"),
                            ("both", "Organisation und Abteilung"),
                        ],
                        max_length=20,
                        verbose_name="Zulässiger Bereich",
                    ),
                ),
                ("is_delegable", models.BooleanField(default=False, verbose_name="Delegierbar nach Freigabe")),
                ("is_archived", models.BooleanField(default=False, verbose_name="Archiviert")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am")),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_template",
                        to="auth.group",
                        verbose_name="Django-Gruppe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rollenvorlage",
                "verbose_name_plural": "Rollenvorlagen",
                "ordering": ["name", "key"],
            },
        ),
        migrations.AddConstraint(
            model_name="roletemplate",
            constraint=models.CheckConstraint(
                check=models.Q(("template_version__gte", 1)), name="role_template_version_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="roletemplate",
            constraint=models.CheckConstraint(
                check=models.Q(("scope__in", ("organization", "department", "both"))), name="role_template_valid_scope"
            ),
        ),
    ]
