# Generated by Django 5.2.17 on 2026-10-06 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("departments", "0004_roletemplate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roletemplate",
            options={
                "ordering": ["name", "key"],
                "permissions": [
                    ("can_assign_roles", "Kann Rollen organisationsweit zuweisen"),
                    ("can_delegate_roles", "Kann freigegebene Abteilungsrollen zuweisen"),
                    ("can_delegate_department_leadership", "Kann Abteilungsleitungen zuweisen"),
                ],
                "verbose_name": "Rollenvorlage",
                "verbose_name_plural": "Rollenvorlagen",
            },
        ),
        migrations.AddField(
            model_name="roletemplate",
            name="delegation_approval",
            field=models.CharField(blank=True, default="", editable=False, max_length=64),
        ),
        migrations.CreateModel(
            name="RoleGrant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source",
                    models.CharField(choices=[("local", "Lokal"), ("ldap", "LDAP"), ("oidc", "OIDC")], max_length=10),
                ),
                ("source_key", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="departments.department"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="role_grants", to="auth.group"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("department__isnull", False)),
                        fields=("user", "group", "department", "source", "source_key"),
                        name="unique_department_role_grant",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("department__isnull", True)),
                        fields=("user", "group", "source", "source_key"),
                        name="unique_organization_role_grant",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source__in", ["local", "ldap", "oidc"])), name="valid_role_grant_source"
                    ),
                ],
            },
        ),
    ]
