# Generated by Django 5.0.14 on 2026-04-29 12:24

import django.db.models.deletion
import training.models.training_media
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("members", "0020_add_gender_to_member"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryBlockCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "color",
                    models.CharField(blank=True, help_text="z.B. #3B82F6", max_length=20, verbose_name="Farbe (Hex)"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="z.B. pi pi-star",
                        max_length=100,
                        verbose_name="Icon (PrimeVue icon name)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bibliotheksblock-Kategorie",
                "verbose_name_plural": "Bibliotheksblock-Kategorien",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LibraryBlockTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LibraryBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "export_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="Export-UUID"),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Titel")),
                ("description", models.TextField(blank=True, verbose_name="Kurzbeschreibung")),
                ("content", models.TextField(blank=True, verbose_name="Inhalt (HTML)")),
                (
                    "default_duration_minutes",
                    models.PositiveIntegerField(default=15, verbose_name="Standard-Dauer (Minuten)"),
                ),
                ("color", models.CharField(blank=True, max_length=20, verbose_name="Farbe (Hex)")),
                ("nextcloud_folder_url", models.URLField(blank=True, verbose_name="Nextcloud-Ordner URL")),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Für zukünftige Bibliotheks-Freigabe", verbose_name="Öffentlich"
                    ),
                ),
                (
                    "source_instance_url",
                    models.URLField(
                        blank=True,
                        help_text="Gesetzt wenn der Block aus einer anderen Instanz importiert wurde",
                        verbose_name="Import-Quelle (URL)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_library_blocks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocks",
                        to="training.libraryblockcategory",
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="blocks", to="training.libraryblocktag", verbose_name="Tags"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bibliotheksblock",
                "verbose_name_plural": "Bibliotheksblöcke",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="TrainingMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                (
                    "file",
                    models.ImageField(
                        upload_to=training.models.training_media.training_media_upload_path, verbose_name="Bild"
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255, verbose_name="Originaldateiname")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Hochgeladen von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trainings-Mediendatei",
                "verbose_name_plural": "Trainings-Mediendateien",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=300, verbose_name="Titel")),
                ("description", models.TextField(blank=True, verbose_name="Beschreibung")),
                ("date", models.DateField(verbose_name="Datum")),
                ("start_time", models.TimeField(verbose_name="Beginn")),
                ("end_time", models.TimeField(verbose_name="Ende")),
                ("location", models.CharField(blank=True, max_length=300, verbose_name="Ort")),
                ("notes", models.TextField(blank=True, verbose_name="Notizen")),
                (
                    "recurrence_rule",
                    models.JSONField(
                        blank=True,
                        help_text='{"frequency": "WEEKLY|BIWEEKLY|MONTHLY", "end_date": "YYYY-MM-DD"}',
                        null=True,
                        verbose_name="Wiederholungsregel",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_training_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leerlassen = Alle Gruppen",
                        related_name="training_sessions",
                        to="members.group",
                        verbose_name="Gruppen",
                    ),
                ),
                (
                    "series_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="series_children",
                        to="training.trainingsession",
                        verbose_name="Serienvorlage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trainingseinheit",
                "verbose_name_plural": "Trainingseinheiten",
                "ordering": ["-date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="TrainingBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=300, verbose_name="Titel")),
                ("content", models.TextField(blank=True, verbose_name="Inhalt (HTML)")),
                ("duration_minutes", models.PositiveIntegerField(default=15, verbose_name="Dauer (Minuten)")),
                (
                    "start_offset_minutes",
                    models.IntegerField(default=0, verbose_name="Start-Offset (Minuten vom Beginn der Einheit)"),
                ),
                (
                    "position_order",
                    models.IntegerField(default=0, verbose_name="Position (für Sortierung auf gleicher Zeitachse)"),
                ),
                ("color", models.CharField(blank=True, max_length=20, verbose_name="Farbe (Hex)")),
                ("nextcloud_folder_url", models.URLField(blank=True, verbose_name="Nextcloud-Ordner URL")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leerlassen = Block gilt für alle Gruppen (Full-Width Swimlane)",
                        related_name="training_blocks",
                        to="members.group",
                        verbose_name="Gruppen",
                    ),
                ),
                (
                    "library_block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_blocks",
                        to="training.libraryblock",
                        verbose_name="Bibliotheksblock (Vorlage)",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="training.trainingsession",
                        verbose_name="Trainingseinheit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trainingsblock",
                "verbose_name_plural": "Trainingsblöcke",
                "ordering": ["session", "start_offset_minutes", "position_order"],
            },
        ),
    ]
