# Generated by Django 5.2.17 on 2026-10-06 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0006_preserve_assignment_sources"),
        ("members", "0033_memberlist_organization_wide"),
        ("training", "0006_training_series_identity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=300, verbose_name="Titel")),
                ("description", models.TextField(blank=True, verbose_name="Beschreibung")),
                ("start_time", models.TimeField(verbose_name="Beginn")),
                ("end_time", models.TimeField(verbose_name="Ende")),
                ("location", models.CharField(blank=True, max_length=300, verbose_name="Ort")),
                ("notes", models.TextField(blank=True, verbose_name="Notizen")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_training_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_templates",
                        to="departments.department",
                        verbose_name="Abteilung",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="training_templates", to="members.group", verbose_name="Gruppen"
                    ),
                ),
                (
                    "source_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_templates",
                        to="training.trainingsession",
                        verbose_name="Ursprüngliche Übung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Übungsvorlage",
                "verbose_name_plural": "Übungsvorlagen",
                "ordering": ["title", "pk"],
            },
        ),
        migrations.CreateModel(
            name="TrainingTemplateBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=300, verbose_name="Titel")),
                ("content", models.TextField(blank=True, verbose_name="Inhalt (HTML)")),
                ("duration_minutes", models.PositiveIntegerField(default=15, verbose_name="Dauer (Minuten)")),
                (
                    "start_offset_minutes",
                    models.IntegerField(default=0, verbose_name="Start-Offset (Minuten vom Beginn der Einheit)"),
                ),
                (
                    "position_order",
                    models.IntegerField(default=0, verbose_name="Position (für Sortierung auf gleicher Zeitachse)"),
                ),
                ("color", models.CharField(blank=True, max_length=20, verbose_name="Farbe (Hex)")),
                ("nextcloud_folder_url", models.URLField(blank=True, verbose_name="Nextcloud-Ordner URL")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="training_template_blocks", to="members.group", verbose_name="Gruppen"
                    ),
                ),
                (
                    "library_block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_blocks",
                        to="training.libraryblock",
                        verbose_name="Bibliotheksblock (Herkunft)",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="training.trainingtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vorlagenbaustein",
                "verbose_name_plural": "Vorlagenbausteine",
                "ordering": ["template", "start_offset_minutes", "position_order", "pk"],
            },
        ),
    ]
