# Generated by Django 5.2.17 on 2026-10-06 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0016_transaction_immutable_trigger"),
        ("training", "0007_training_templates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingblock",
            name="instructors",
            field=models.ManyToManyField(
                blank=True,
                related_name="instructed_training_blocks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ausbilder",
            ),
        ),
        migrations.AddField(
            model_name="trainingblock",
            name="kind",
            field=models.CharField(
                choices=[
                    ("block", "Baustein"),
                    ("station", "Station"),
                    ("transition", "Wechsel"),
                    ("break", "Pause"),
                    ("free", "Freie Runde"),
                ],
                default="block",
                max_length=12,
                verbose_name="Art",
            ),
        ),
        migrations.AddField(
            model_name="trainingblock",
            name="learning_objective",
            field=models.TextField(blank=True, verbose_name="Lernziel"),
        ),
        migrations.AddField(
            model_name="trainingblock",
            name="location",
            field=models.CharField(blank=True, max_length=300, verbose_name="Ort"),
        ),
        migrations.AddField(
            model_name="trainingblock",
            name="safety_notes",
            field=models.TextField(blank=True, verbose_name="Sicherheitshinweise"),
        ),
        migrations.AddField(
            model_name="trainingtemplateblock",
            name="instructors",
            field=models.ManyToManyField(
                blank=True,
                related_name="instructed_training_template_blocks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ausbilder",
            ),
        ),
        migrations.AddField(
            model_name="trainingtemplateblock",
            name="kind",
            field=models.CharField(
                choices=[
                    ("block", "Baustein"),
                    ("station", "Station"),
                    ("transition", "Wechsel"),
                    ("break", "Pause"),
                    ("free", "Freie Runde"),
                ],
                default="block",
                max_length=12,
                verbose_name="Art",
            ),
        ),
        migrations.AddField(
            model_name="trainingtemplateblock",
            name="learning_objective",
            field=models.TextField(blank=True, verbose_name="Lernziel"),
        ),
        migrations.AddField(
            model_name="trainingtemplateblock",
            name="location",
            field=models.CharField(blank=True, max_length=300, verbose_name="Ort"),
        ),
        migrations.AddField(
            model_name="trainingtemplateblock",
            name="safety_notes",
            field=models.TextField(blank=True, verbose_name="Sicherheitshinweise"),
        ),
        migrations.CreateModel(
            name="TrainingBlockMaterial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="Menge")),
                ("label", models.CharField(blank=True, max_length=200, verbose_name="Bezeichnung")),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="training.trainingblock",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inventory.item",
                        verbose_name="Artikel",
                    ),
                ),
                (
                    "template_block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="training.trainingtemplateblock",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inventory.itemvariant",
                        verbose_name="Variante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Materialbedarf",
                "verbose_name_plural": "Materialbedarfe",
                "ordering": ["pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("block__isnull", False), ("template_block__isnull", True)),
                            models.Q(("block__isnull", True), ("template_block__isnull", False)),
                            _connector="OR",
                        ),
                        name="training_material_single_owner",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gte", 1)), name="training_material_positive_quantity"
                    ),
                ],
            },
        ),
    ]
