# Generated by Django 5.2.18 on 2026-10-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0009_training_publish_justification"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingblock",
            name="station_key",
            field=models.UUIDField(blank=True, null=True, verbose_name="Stationsverknüpfung"),
        ),
        migrations.AddField(
            model_name="trainingtemplateblock",
            name="station_key",
            field=models.UUIDField(blank=True, null=True, verbose_name="Stationsverknüpfung"),
        ),
    ]
