# Generated by Django 5.2.18 on 2026-10-07 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0010_training_station_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingDebrief",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("actual_start", models.TimeField(blank=True, null=True, verbose_name="Tatsächlicher Beginn")),
                ("actual_end", models.TimeField(blank=True, null=True, verbose_name="Tatsächliches Ende")),
                ("reflection", models.TextField(blank=True, verbose_name="Reflexion")),
                ("improvements", models.TextField(blank=True, verbose_name="Verbesserungshinweise")),
                ("revision", models.PositiveIntegerField(default=0, editable=False, verbose_name="Version")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debrief",
                        to="training.trainingsession",
                        verbose_name="Übung",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nachbereitung",
                "verbose_name_plural": "Nachbereitungen",
            },
        ),
    ]
