"""
Django settings for jf_manager_backend project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

import environ

from .encryption_config import cache_key_prefix, encryption_keys

# Build paths inside the project like this: BASE_DIR / 'subdir'
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# Explicit primary key and optional old keys for controlled rotation.
FIELD_ENCRYPTION_KEY = encryption_keys(os.environ)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() in ("true", "1", "yes")

if not DEBUG and not SECRET_KEY:
    raise Exception("DJANGO_SECRET_KEY must be set in production (DEBUG=False)")

AUDIT_RETENTION_DAYS = max(1, int(os.environ.get("AUDIT_RETENTION_DAYS", "180")))
# Replay window for booking idempotency keys; stored responses contain booking details.
BOOKING_REPLAY_RETENTION_DAYS = max(1, int(os.environ.get("BOOKING_REPLAY_RETENTION_DAYS", "30")))

ALLOWED_HOSTS = [h.strip() for h in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h.strip()]


def _env_flag(name, default):
    return os.environ.get(name, "true" if default else "false").strip().lower() in ("true", "1", "yes")


# Nginx forwards the original scheme when TLS terminates at a reverse proxy.
# Only trust it when every request passes through a proxy that overwrites
# X-Forwarded-Proto; direct access to the backend must then be impossible.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https") if _env_flag("TRUST_PROXY_SSL_HEADER", True) else None

# CSRF Trusted Origins - required for POST requests from frontend
# Must include full URL scheme (https:// or http://)
CSRF_TRUSTED_ORIGINS_ENV = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in CSRF_TRUSTED_ORIGINS_ENV.split(",") if origin.strip()]

# Frontend URL for password reset emails
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:5173")
# Passkeys (SEC-11): relying party and accepted origins; both default to the
# address of FRONTEND_URL. Changing the domain invalidates registered passkeys.
WEBAUTHN_RP_ID = os.environ.get("WEBAUTHN_RP_ID", "")
WEBAUTHN_ORIGINS = [o.strip() for o in os.environ.get("WEBAUTHN_ORIGINS", "").split(",") if o.strip()]

# CORS settings for Vue.js frontend
CORS_ALLOWED_ORIGINS_ENV = os.environ.get("CORS_ALLOWED_ORIGINS", "")
CORS_ALLOWED_ORIGINS = (
    [o.strip() for o in CORS_ALLOWED_ORIGINS_ENV.split(",") if o.strip()]
    if CORS_ALLOWED_ORIGINS_ENV
    else [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]
)

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = DEBUG

env = environ.Env(
    REDIS_URL=(str, "none"),
)

# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.admin",
    # Third party apps
    "corsheaders",
    "dynamic_preferences",
    "guardian",
    "mptt",
    "rest_framework",
    "drf_spectacular",
    "django_filters",
    "import_export",
    "django_cleanup.apps.CleanupConfig",
    "phonenumber_field",
    "colorfield",
    # Project apps
    "departments.apps.DepartmentsConfig",
    "users.apps.UsersConfig",
    "inventory.apps.InventoryConfig",
    "members.apps.MembersConfig",
    "servicebook.apps.ServicebookConfig",
    "orders.apps.OrdersConfig",
    "qualifications.apps.QualificationsConfig",
    "training.apps.TrainingConfig",
    "external_sync.apps.ExternalSyncConfig",
    "settings_manager.apps.SettingsManagerConfig",
    "django_rq",
    "health",
    "notifications.apps.NotificationsConfig",
    "mozilla_django_oidc",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "users.session_policy.SessionPolicyMiddleware",
    "users.mfa_policy.MFAPolicyMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "jf_manager_backend.email_middleware.EmailConfigMiddleware",
]

ROOT_URLCONF = "jf_manager_backend.urls"


STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Media files configuration
MEDIA_URL = "/uploads/"
MEDIA_ROOT = os.path.join(BASE_DIR, "uploads")

# Upload folder configuration (can be overridden via environment variables)
MEMBER_UPLOAD_FOLDER = os.environ.get("MEMBER_UPLOAD_FOLDER", "members/avatars")
ATTACHMENT_UPLOAD_FOLDER = os.environ.get("ATTACHMENT_UPLOAD_FOLDER", "attachments")

SITE_ID = 1


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "dynamic_preferences.processors.global_preferences",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
LOGIN_REDIRECT_URL = "/admin/"
LOGOUT_REDIRECT_URL = "/admin/login/"
AUTH_USER_MODEL = "users.CustomUser"
LOGIN_URL = "/admin/login/"

WSGI_APPLICATION = "jf_manager_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Verwende BigAutoField als Standard um W042 Warnungen zu beseitigen
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Session Serializer auf JSON setzen (robuster, verhindert Pickle Probleme)
SESSION_SERIALIZER = "django.contrib.sessions.serializers.JSONSerializer"

# Browser sessions: host-only cookies, never readable by scripts. Secure by
# default; only an explicit development override may disable it.
_SECURE_COOKIES = _env_flag("SECURE_COOKIES", not DEBUG)
SESSION_COOKIE_SECURE = _SECURE_COOKIES
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_DOMAIN = None
# The SPA reads the CSRF cookie and returns it as X-CSRFToken.
CSRF_COOKIE_SECURE = _SECURE_COOKIES
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_DOMAIN = None

# Transport security. HTTPS is mandatory whenever cookies are secure; the
# container health check calls the backend directly over HTTP.
SECURE_SSL_REDIRECT = _env_flag("SECURE_SSL_REDIRECT", _SECURE_COOKIES)
SECURE_REDIRECT_EXEMPT = [r"^health/$"]
SECURE_HSTS_SECONDS = max(0, int(os.environ.get("SECURE_HSTS_SECONDS", "31536000" if _SECURE_COOKIES else "0")))
# Subdomains of the organisation's domain may still be served over HTTP, so
# extending HSTS to them (and preloading) stays an explicit decision.
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_flag("SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = _env_flag("SECURE_HSTS_PRELOAD", False)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"
SILENCED_SYSTEM_CHECKS = [
    "security.W005",  # HSTS includeSubDomains, see above
    "security.W021",  # HSTS preload, see above
]


def _bounded_seconds(name, default, minimum, maximum):
    try:
        value = int(os.environ.get(name, default))
    except ValueError as exc:
        raise Exception(f"{name} muss eine ganze Zahl (Sekunden) sein.") from exc
    return max(minimum, min(maximum, value))


# Ordinary accounts: long-running sessions (default 30 days idle, 90 days
# absolute); actions that widen access need a fresh confirmation instead.
# Accounts with mandatory MFA (admins, leadership): default 8 hours.
# Enforced server-side by users.session_policy; values are clamped.
SESSION_IDLE_TIMEOUT_SECONDS = _bounded_seconds("SESSION_IDLE_TIMEOUT_SECONDS", 30 * 86400, 300, 90 * 86400)
SESSION_MAX_AGE_SECONDS = _bounded_seconds("SESSION_MAX_AGE_SECONDS", 90 * 86400, 3600, 365 * 86400)
PRIVILEGED_SESSION_IDLE_TIMEOUT_SECONDS = _bounded_seconds(
    "PRIVILEGED_SESSION_IDLE_TIMEOUT_SECONDS", 8 * 3600, 300, 86400
)
PRIVILEGED_SESSION_MAX_AGE_SECONDS = _bounded_seconds("PRIVILEGED_SESSION_MAX_AGE_SECONDS", 8 * 3600, 3600, 7 * 86400)
SESSION_COOKIE_AGE = SESSION_MAX_AGE_SECONDS
CONFIGURATION_ENV_OVERRIDES = frozenset(
    name
    for name in (
        "SESSION_IDLE_TIMEOUT_SECONDS",
        "SESSION_MAX_AGE_SECONDS",
        "PRIVILEGED_SESSION_IDLE_TIMEOUT_SECONDS",
        "PRIVILEGED_SESSION_MAX_AGE_SECONDS",
    )
    if name in os.environ
)

AUTHENTICATION_BACKENDS = (
    "users.ldap_backend.ConfigurableLDAPBackend",
    "users.oidc_backend.JFManagerOIDCBackend",
    "django.contrib.auth.backends.ModelBackend",
    "guardian.backends.ObjectPermissionBackend",
)

# OIDC settings for mozilla-django-oidc
# Endpoints are read from DB at runtime in JFManagerOIDCBackend.get_settings().
# Static defaults required by the library:
LOGIN_REDIRECT_URL_FAILURE = "/login/"
OIDC_STORE_ACCESS_TOKEN = False
OIDC_STORE_ID_TOKEN = False
OIDC_AUTHENTICATION_CALLBACK_URL = "oidc-callback"
# Allow RS256 (most providers) and HS256
OIDC_RP_SIGN_ALGO = "RS256"
# JWKS URI is fetched automatically from the discovery document at callback time
OIDC_OP_JWKS_ENDPOINT = ""  # populated at runtime from discovery
OIDC_OP_AUTHORIZATION_ENDPOINT = ""  # populated at runtime from discovery
OIDC_OP_TOKEN_ENDPOINT = ""  # populated at runtime from discovery
OIDC_OP_USER_ENDPOINT = ""  # populated at runtime from discovery
OIDC_RP_CLIENT_ID = ""  # populated at runtime from DB
OIDC_RP_CLIENT_SECRET = ""  # populated at runtime from DB

REST_FRAMEWORK = {
    # Browser sessions only; JWT and DRF tokens were retired in SEC-07.7.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "users.session_auth.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "jf_manager_backend.permissions.CustomDefaultPermissions",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 100,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# Password reset links expire after one hour.
PASSWORD_RESET_TIMEOUT = 3600

# drf-spectacular settings for API documentation
SPECTACULAR_SETTINGS = {
    "TITLE": "JF-Manager API",
    "DESCRIPTION": "API documentation for the Jugendfeuerwehr Manager",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": "/api/v1/",
    # Schema completeness is not a deployment safety check; keep
    # `check --deploy` focused on security settings.
    "ENABLE_DJANGO_DEPLOY_CHECK": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SERVE_AUTHENTICATION": [
        "users.session_auth.SessionAuthentication",
    ],
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
        "filter": True,
    },
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
}

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = "de-de"

TIME_ZONE = os.environ.get("TIME_ZONE", "Europe/Berlin")

USE_I18N = True

USE_L10N = True

USE_TZ = True

TEST_RUNNER = "jf_manager_backend.test_runner.CacheIsolatedRunner"


# Cache configuration
# Default to local memory cache for development
REDIS_URL = env("REDIS_URL", default="none")
if REDIS_URL != "none":
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
            "KEY_PREFIX": cache_key_prefix(FIELD_ENCRYPTION_KEY),
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }

if REDIS_URL != "none":
    RQ_QUEUES = {
        "default": {
            "URL": REDIS_URL,
            "DEFAULT_TIMEOUT": 3600,
        }
    }
else:
    RQ_QUEUES = {}
# Default email settings (can be overridden by dynamic preferences)
EMAIL_HOST = ""
EMAIL_PORT = 587
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = "webmaster@localhost"

# For development - use console backend to see emails in terminal
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO" if not DEBUG else "DEBUG",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "WARNING" if not DEBUG else "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

# Web Push: opt-in per device; private key never leaves the backend.
WEB_PUSH_PUBLIC_KEY = os.environ.get("WEB_PUSH_PUBLIC_KEY", "")
WEB_PUSH_PRIVATE_KEY = os.environ.get("WEB_PUSH_PRIVATE_KEY", "")
WEB_PUSH_SUBJECT = os.environ.get("WEB_PUSH_SUBJECT", "")
WEB_PUSH_ALLOWED_HOSTS = [
    "fcm.googleapis.com",
    "updates.push.services.mozilla.com",
    "push.services.mozilla.com",
    "web.push.apple.com",
    "notify.windows.com",
]
