# Generated by Django 2.1.5 on 2019-07-18 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190718_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': (('can_rent', 'can rent items to members'),)},
        ),
    ]
