# Generated by Django 5.0.11 on 2025-08-31 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_category_options_alter_item_options_and_more'),
        ('members', '0014_member_storage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Übergeordneter Lagerort für hierarchische Struktur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.storagelocation', verbose_name='Übergeordneter Lagerort'),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='member',
            field=models.OneToOneField(blank=True, help_text='Verknüpftes Mitglied, falls is_member=True', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_storage_location', to='members.member', verbose_name='Mitglied'),
        ),
    ]
