# Generated by Django 5.0.14 on 2025-09-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Einstellungskategorie',
                'verbose_name_plural': 'Einstellungskategorien',
                'permissions': [('view_general_settings', 'Kann allgemeine Einstellungen einsehen'), ('change_general_settings', 'Kann allgemeine Einstellungen ändern'), ('view_email_settings', 'Kann E-Mail Einstellungen einsehen'), ('change_email_settings', 'Kann E-Mail Einstellungen ändern'), ('view_member_settings', 'Kann Mitglieder Einstellungen einsehen'), ('change_member_settings', 'Kann Mitglieder Einstellungen ändern'), ('view_service_settings', 'Kann Dienst Einstellungen einsehen'), ('change_service_settings', 'Kann Dienst Einstellungen ändern'), ('view_order_settings', 'Kann Bestell Einstellungen einsehen'), ('change_order_settings', 'Kann Bestell Einstellungen ändern'), ('view_all_settings', 'Kann alle Einstellungen einsehen'), ('change_all_settings', 'Kann alle Einstellungen ändern')],
            },
        ),
    ]
