# Generated by Django 5.0.14 on 2026-05-04 18:19

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LDAPConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enabled", models.BooleanField(default=False, verbose_name="LDAP aktiviert")),
                (
                    "server_uri",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="LDAP Server URI"),
                ),
                ("start_tls", models.BooleanField(default=False, verbose_name="STARTTLS verwenden")),
                ("bind_dn", models.CharField(blank=True, default="", max_length=255, verbose_name="Bind DN")),
                (
                    "bind_password",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="Bind Passwort"
                    ),
                ),
                (
                    "user_search_base_dn",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Benutzer Such-Basis DN"),
                ),
                (
                    "user_search_filter",
                    models.CharField(
                        default="(uid=%(user)s)",
                        help_text="z.B. (uid=%(user)s) oder (sAMAccountName=%(user)s)",
                        max_length=255,
                        verbose_name="Benutzer Such-Filter",
                    ),
                ),
                (
                    "group_search_base_dn",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Gruppen OU / Basis DN"),
                ),
                (
                    "group_search_filter",
                    models.CharField(
                        default="(objectClass=groupOfNames)", max_length=255, verbose_name="Gruppen Such-Filter"
                    ),
                ),
                (
                    "group_type",
                    models.CharField(
                        choices=[("group_of_names", "GroupOfNames"), ("active_directory", "ActiveDirectory")],
                        default="group_of_names",
                        max_length=32,
                        verbose_name="Gruppen Typ",
                    ),
                ),
                (
                    "mirror_groups",
                    models.BooleanField(
                        default=True,
                        help_text="Spiegelt LDAP Gruppen als Django auth.Group bei Login.",
                        verbose_name="LDAP Gruppen spiegeln",
                    ),
                ),
                (
                    "require_group",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional: Nur Benutzer dieser LDAP Gruppe dürfen sich anmelden.",
                        max_length=255,
                        verbose_name="Require Group DN",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "LDAP Konfiguration",
                "verbose_name_plural": "LDAP Konfiguration",
            },
        ),
        migrations.AlterModelOptions(
            name="settingscategory",
            options={
                "permissions": [
                    ("view_general_settings", "Kann allgemeine Einstellungen einsehen"),
                    ("change_general_settings", "Kann allgemeine Einstellungen ändern"),
                    ("view_email_settings", "Kann E-Mail Einstellungen einsehen"),
                    ("change_email_settings", "Kann E-Mail Einstellungen ändern"),
                    ("view_member_settings", "Kann Mitglieder Einstellungen einsehen"),
                    ("change_member_settings", "Kann Mitglieder Einstellungen ändern"),
                    ("view_service_settings", "Kann Dienst Einstellungen einsehen"),
                    ("change_service_settings", "Kann Dienst Einstellungen ändern"),
                    ("view_order_settings", "Kann Bestell Einstellungen einsehen"),
                    ("change_order_settings", "Kann Bestell Einstellungen ändern"),
                    ("view_ldap_settings", "Kann LDAP Einstellungen einsehen"),
                    ("change_ldap_settings", "Kann LDAP Einstellungen ändern"),
                    ("view_all_settings", "Kann alle Einstellungen einsehen"),
                    ("change_all_settings", "Kann alle Einstellungen ändern"),
                ],
                "verbose_name": "Einstellungskategorie",
                "verbose_name_plural": "Einstellungskategorien",
            },
        ),
    ]
