# Generated by Django 5.0.14 on 2026-05-04 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("departments", "0003_department_color"),
        ("settings_manager", "0002_ldapconfig_alter_settingscategory_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="LDAPDepartmentRoleMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "ldap_group_dn",
                    models.CharField(
                        help_text="Vollständiger DN der LDAP-Gruppe, z.B. cn=admins,ou=groups,dc=example,dc=org. Benutzer in dieser Gruppe erhalten automatisch die konfigurierte Abteilungs-Rolle.",
                        max_length=500,
                        verbose_name="LDAP Gruppen-DN",
                    ),
                ),
                (
                    "revoke_on_mismatch",
                    models.BooleanField(
                        default=False,
                        help_text="Falls aktiviert, wird die Abteilungs-Rolle beim nächsten Login automatisch entfernt, wenn der Benutzer nicht (mehr) Mitglied der LDAP-Gruppe ist. Standardmäßig deaktiviert: einmal zugewiesene Rollen bleiben erhalten.",
                        verbose_name="Rolle entfernen wenn nicht (mehr) in LDAP-Gruppe",
                    ),
                ),
                (
                    "auth_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Django-Gruppen, die dem Benutzer in dieser Abteilung zugewiesen werden. Diese Gruppen steuern, welche Aktionen der Benutzer in der Abteilung ausführen darf.",
                        related_name="ldap_role_mappings",
                        to="auth.group",
                        verbose_name="Berechtigungsgruppen",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ldap_role_mappings",
                        to="departments.department",
                        verbose_name="Abteilung",
                    ),
                ),
                (
                    "ldap_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_role_mappings",
                        to="settings_manager.ldapconfig",
                        verbose_name="LDAP Konfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "LDAP Abteilungs-Rollen-Mapping",
                "verbose_name_plural": "LDAP Abteilungs-Rollen-Mappings",
                "ordering": ["department__name", "ldap_group_dn"],
                "unique_together": {("ldap_config", "ldap_group_dn", "department")},
            },
        ),
    ]
