# Generated by Django 5.0.14 on 2026-05-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings_manager", "0004_oidcconfig_oidcgroupmapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="ldapconfig",
            name="ca_cert_content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional: PEM-Inhalt eines CA-Zertifikats für LDAP TLS.",
                verbose_name="CA Zertifikat (Inhalt)",
            ),
        ),
        migrations.AddField(
            model_name="ldapconfig",
            name="ca_cert_file",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional: Dateipfad zu einer CA-Zertifikatsdatei für LDAP TLS.",
                max_length=512,
                verbose_name="CA Zertifikat (Dateipfad)",
            ),
        ),
        migrations.AddField(
            model_name="ldapconfig",
            name="disable_cert_validation",
            field=models.BooleanField(
                default=False,
                help_text="Nicht empfohlen: Deaktiviert die TLS Zertifikatsprüfung für LDAP Verbindungen.",
                verbose_name="TLS Zertifikatsprüfung deaktivieren",
            ),
        ),
    ]
