# Generated by Django 5.0.14 on 2026-05-11 17:48

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("settings_manager", "0005_ldapconfig_ca_cert_content_ldapconfig_ca_cert_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oidcconfig",
            name="admin_group",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nutzer in dieser Gruppe erhalten automatisch is_superuser=True. Leer lassen, um kein automatisches Superuser-Mapping vorzunehmen.",
                max_length=255,
                verbose_name="Admin-Gruppe",
            ),
        ),
        migrations.AlterField(
            model_name="oidcconfig",
            name="client_secret",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="Das Client-Secret aus der OIDC-Provider-Konfiguration. Wird verschlüsselt gespeichert.",
                verbose_name="Client Secret",
            ),
        ),
        migrations.AlterField(
            model_name="oidcconfig",
            name="groups_claim",
            field=models.CharField(
                default="groups",
                help_text="Name des JWT-Claims, der die Gruppen-Zugehörigkeiten des Nutzers enthält. Standard bei Nextcloud OIDC: 'groups'.",
                max_length=100,
                verbose_name="Gruppen-Claim",
            ),
        ),
        migrations.AlterField(
            model_name="oidcconfig",
            name="hide_local_login",
            field=models.BooleanField(
                default=False,
                help_text="Falls aktiviert, wird das lokale Benutzername/Passwort-Formular auf der Login-Seite standardmäßig ausgeblendet. Ein kleiner Link ermöglicht es Administratoren, sich trotzdem mit lokalem Account anzumelden.",
                verbose_name="Lokalen Login ausblenden",
            ),
        ),
        migrations.AlterField(
            model_name="oidcconfig",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="oidcconfig",
            name="issuer_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Die Basis-URL des OIDC Providers. Das Discovery-Dokument wird unter {issuer_url}/.well-known/openid-configuration gesucht. Für Nextcloud z.B. https://nextcloud.example.org.",
                max_length=500,
                verbose_name="Issuer URL",
            ),
        ),
        migrations.AlterField(
            model_name="oidcconfig",
            name="require_group_mapping",
            field=models.BooleanField(
                default=False,
                help_text="Falls aktiviert, wird der Login blockiert, wenn der Nutzer in keiner konfigurierten Gruppen-Zuordnung (OIDC-Gruppen-Mapping) enthalten ist. Standardmäßig deaktiviert: Nutzer erhalten Zugang, auch ohne Abteilungszuweisung.",
                verbose_name="Login nur bei Gruppen-Mapping erlauben",
            ),
        ),
        migrations.AlterField(
            model_name="oidcconfig",
            name="scope",
            field=models.CharField(
                default="openid email profile",
                help_text="Leerzeichen-getrennte OIDC-Scopes. Standard: 'openid email profile'. Für Nextcloud-Gruppen-Claim zusätzlich 'groups' hinzufügen.",
                max_length=255,
                verbose_name="Scopes",
            ),
        ),
        migrations.AlterField(
            model_name="oidcconfig",
            name="staff_group",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nutzer in dieser Gruppe erhalten automatisch is_staff=True (Zugang zum Admin-Bereich). Leer lassen, um kein automatisches Staff-Mapping vorzunehmen.",
                max_length=255,
                verbose_name="Staff-Gruppe",
            ),
        ),
        migrations.AlterField(
            model_name="oidcgroupmapping",
            name="auth_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Django-Gruppen, die dem Nutzer in dieser Abteilung zugewiesen werden. Diese Gruppen steuern, welche Aktionen der Nutzer in der Abteilung ausführen darf.",
                related_name="oidc_group_mappings",
                to="auth.group",
                verbose_name="Berechtigungsgruppen",
            ),
        ),
        migrations.AlterField(
            model_name="oidcgroupmapping",
            name="group_claim_value",
            field=models.CharField(
                help_text="Der Wert im Gruppen-Claim des OIDC-Tokens, z.B. 'jf-admins' oder 'Jugendwart'. Nutzer mit diesem Gruppen-Wert erhalten automatisch die konfigurierte Abteilungs-Rolle.",
                max_length=500,
                verbose_name="Gruppen-Claim Wert",
            ),
        ),
        migrations.AlterField(
            model_name="oidcgroupmapping",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="oidcgroupmapping",
            name="revoke_on_mismatch",
            field=models.BooleanField(
                default=False,
                help_text="Falls aktiviert, wird die Abteilungs-Rolle beim nächsten Login automatisch entfernt, wenn der Nutzer nicht (mehr) in der OIDC-Gruppe ist. Standardmäßig deaktiviert: einmal zugewiesene Rollen bleiben erhalten.",
                verbose_name="Rolle entfernen wenn nicht (mehr) in OIDC-Gruppe",
            ),
        ),
    ]
