# Generated by Django 5.0.14 on 2026-10-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings_manager", "0007_alter_ldapconfig_bind_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oidcconfig",
            name="trust_provider_mfa",
            field=models.BooleanField(
                default=False,
                help_text="Nur aktivieren, wenn der Provider einen zweiten Faktor erzwingt und dies im ID-Token per 'amr'-Claim (z. B. 'mfa', 'otp', 'hwk') bestätigt. Sonst verlangt JF-Manager für MFA-pflichtige Konten zusätzlich den eigenen zweiten Faktor.",
                verbose_name="MFA des Providers anerkennen",
            ),
        ),
    ]
