# Generated by Django 5.2.17 on 2026-10-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings_manager", "0008_oidc_trust_provider_mfa"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettingsWriteLock",
            fields=[
                ("category", models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
    ]
