# Generated by Django 5.2.17 on 2026-10-06 13:19

import jf_manager_backend.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0011_security_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('public_key', models.TextField(blank=True, default='')),
                ('private_key', jf_manager_backend.encrypted_fields.StrictEncryptedCharField(blank=True, default='')),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='push_configuration_singleton')],
            },
        ),
    ]
