# Generated by Django 5.0.14 on 2025-09-01 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0015_alter_event_id_alter_eventtype_id_alter_group_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="z.B. 'Grundlehrgang', 'Sprechfunk'", max_length=200, verbose_name='Name')),
                ('expires', models.BooleanField(default=False, help_text='Wenn aktiviert, ist ein Ablaufdatum erforderlich', verbose_name='Läuft ab')),
                ('validity_period', models.PositiveIntegerField(blank=True, help_text="Standarddauer in Monaten (nur wenn 'Läuft ab' aktiviert ist)", null=True, verbose_name='Gültigkeitsdauer (Monate)')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Qualifikationstyp',
                'verbose_name_plural': 'Qualifikationstypen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialTaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="z.B. 'Jugendsprecher', 'Kleiderwart'", max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Sonderaufgaben-Typ',
                'verbose_name_plural': 'Sonderaufgaben-Typen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_acquired', models.DateField(help_text='Datum des Erwerbs der Qualifikation', verbose_name='Erworben am')),
                ('date_expires', models.DateField(blank=True, help_text='Ablaufdatum (falls erforderlich)', null=True, verbose_name='Läuft ab am')),
                ('issued_by', models.CharField(blank=True, help_text='Organisation oder Person, die die Qualifikation ausgestellt hat', max_length=200, verbose_name='Ausgestellt von')),
                ('note', models.TextField(blank=True, verbose_name='Notiz')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='members.member', verbose_name='Mitglied')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualifications.qualificationtype', verbose_name='Qualifikationstyp')),
            ],
            options={
                'verbose_name': 'Qualifikation',
                'verbose_name_plural': 'Qualifikationen',
                'ordering': ['-date_acquired'],
                'permissions': [('view_all_qualifications', 'Kann alle Qualifikationen einsehen'), ('manage_qualifications', 'Kann Qualifikationen verwalten')],
            },
        ),
        migrations.CreateModel(
            name='SpecialTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Datum des Beginns der Aufgabe', verbose_name='Startdatum')),
                ('end_date', models.DateField(blank=True, help_text='Datum des Endes der Aufgabe (leer = noch aktiv)', null=True, verbose_name='Enddatum')),
                ('note', models.TextField(blank=True, verbose_name='Notiz')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_tasks', to='members.member', verbose_name='Mitglied')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualifications.specialtasktype', verbose_name='Aufgabe')),
            ],
            options={
                'verbose_name': 'Sonderaufgabe',
                'verbose_name_plural': 'Sonderaufgaben',
                'ordering': ['-start_date'],
                'permissions': [('view_all_specialtasks', 'Kann alle Sonderaufgaben einsehen'), ('manage_specialtasks', 'Kann Sonderaufgaben verwalten')],
            },
        ),
    ]
