# Generated by Django 5.2.18 on 2026-10-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qualifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualificationtype",
            name="includes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Wer diese Qualifikation hat, erfüllt auch die hier gewählten (z. B. Truppführer schließt Truppmann ein)",
                related_name="included_by",
                to="qualifications.qualificationtype",
                verbose_name="Schließt ein",
            ),
        ),
    ]
