# Generated by Django 2.1.3 on 2019-02-27 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, default='', max_length=100, verbose_name='Größe ')),
                ('identifier1', models.CharField(blank=True, default='', max_length=255, verbose_name='Inventarnummer 1')),
                ('identifier2', models.CharField(blank=True, default='', max_length=255, verbose_name='Inventarnummer 2')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Category', verbose_name='Kategorie')),
                ('rented_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Member', verbose_name='Ausgeliehen von')),
            ],
        ),
    ]
