# Generated by Django 2.1.5 on 2019-07-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190304_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': (('can_rent', 'Darf Invetargegenstände an Mitglieder ausgeben / zurücknehmen'),)},
        ),
    ]
