# Generated by Django 5.0.11 on 2025-08-31 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190718_2046'),
        ('members', '0013_alter_status_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorien'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'permissions': [('can_rent', 'can rent items to members')], 'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikel'},
        ),
        migrations.AddField(
            model_name='category',
            name='schema',
            field=models.JSONField(blank=True, help_text='Variable Attribute pro Kategorie (z.B. {"größe": "string", "farbe": "string"})', null=True, verbose_name='Schema'),
        ),
        migrations.AddField(
            model_name='item',
            name='attributes',
            field=models.JSONField(blank=True, help_text='Spezifische Attribute (z.B. {"größe": "L", "farbe": "rot"})', null=True, verbose_name='Attribute'),
        ),
        migrations.AddField(
            model_name='item',
            name='base_unit',
            field=models.CharField(default='Stück', max_length=50, verbose_name='Grundeinheit'),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.category', verbose_name='Kategorie'),
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('is_member', models.BooleanField(default=False, help_text='Markiert diesen Ort als Mitglied-Lagerort', verbose_name='Ist Mitglied')),
                ('member', models.OneToOneField(blank=True, help_text='Verknüpftes Mitglied, falls is_member=True', null=True, on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='Mitglied')),
            ],
            options={
                'verbose_name': 'Lagerort',
                'verbose_name_plural': 'Lagerorte',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Eingang'), ('OUT', 'Ausgang'), ('MOVE', 'Umlagerung'), ('LOAN', 'Ausleihe'), ('RETURN', 'Rückgabe'), ('DISCARD', 'Aussortierung')], max_length=10, verbose_name='Transaktionstyp')),
                ('quantity', models.PositiveIntegerField(verbose_name='Menge')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Datum')),
                ('note', models.TextField(blank=True, verbose_name='Notiz')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='Artikel')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='inventory.storagelocation', verbose_name='Quelle')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='inventory.storagelocation', verbose_name='Ziel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Transaktion',
                'verbose_name_plural': 'Transaktionen',
                'ordering': ['-date'],
                'permissions': [('discard_items', 'Can discard items')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Menge')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='Artikel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.storagelocation', verbose_name='Lagerort')),
            ],
            options={
                'verbose_name': 'Bestand',
                'verbose_name_plural': 'Bestände',
                'unique_together': {('item', 'location')},
            },
        ),
    ]
