# Generated by Django 5.0.11 on 2025-08-31 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_add_storage_hierarchy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='item',
            name='is_variant_parent',
            field=models.BooleanField(default=False, help_text='Markieren Sie dies, wenn dieser Artikel Varianten hat (z.B. verschiedene Größen)', verbose_name='Hat Varianten'),
        ),
        migrations.AlterField(
            model_name='item',
            name='attributes',
            field=models.JSONField(blank=True, help_text='Grundlegende Attribute des Artikels (z.B. {"marke": "Adidas", "typ": "Hose"})', null=True, verbose_name='Basis-Attribute'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='Artikel'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='Artikel'),
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_attributes', models.JSONField(help_text='Spezifische Attribute dieser Variante (z.B. {"größe": "164", "farbe": "blau"})', verbose_name='Varianten-Attribute')),
                ('sku', models.CharField(blank=True, help_text='Eindeutige Artikelnummer für diese Variante', max_length=100, verbose_name='SKU/Artikelnummer')),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.item', verbose_name='Hauptartikel')),
            ],
            options={
                'verbose_name': 'Artikel-Variante',
                'verbose_name_plural': 'Artikel-Varianten',
                'ordering': ['parent_item__name', 'sku'],
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='item_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemvariant', verbose_name='Artikel-Variante'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='item_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.itemvariant', verbose_name='Artikel-Variante'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('item__isnull', False), ('item_variant__isnull', True)), models.Q(('item__isnull', True), ('item_variant__isnull', False)), _connector='OR'), name='stock_either_item_or_variant'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('item__isnull', False), ('item_variant__isnull', True)), models.Q(('item__isnull', True), ('item_variant__isnull', False)), _connector='OR'), name='transaction_either_item_or_variant'),
        ),
        migrations.AlterUniqueTogether(
            name='itemvariant',
            unique_together={('parent_item', 'variant_attributes')},
        ),
    ]
