# Generated by Django 5.0.14 on 2026-05-01 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0001_initial"),
        ("inventory", "0009_transaction_discard_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_items",
                to="departments.department",
                verbose_name="Abteilung",
            ),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="storage_locations",
                to="departments.department",
                verbose_name="Abteilung",
            ),
        ),
    ]
