# Generated by Django 5.0.14 on 2026-07-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_item_department_storagelocation_department"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-date"],
                "permissions": [
                    ("discard_items", "Can discard items"),
                    ("clear_former_member_names", "Can clear former member names from transactions"),
                ],
                "verbose_name": "Transaktion",
                "verbose_name_plural": "Transaktionen",
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="former_member_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name des Mitglieds, das zum Zeitpunkt der Transaktion verknüpft war (wird gesetzt, wenn ein Mitglied gelöscht wird)",
                max_length=255,
                verbose_name="Ehemaliges Mitglied",
            ),
        ),
    ]
