# Generated by Django 5.0.14 on 2026-10-04 17:29

from django.db import migrations, models
from django.db.models import Count


def verify_stock_identity(apps, schema_editor):
    Stock = apps.get_model("inventory", "Stock")
    database = schema_editor.connection.alias
    duplicate_keys = (
        Stock.objects.using(database)
        .values("location_id", "item_id", "item_variant_id")
        .annotate(rows=Count("pk"))
        .filter(rows__gt=1)
        .count()
    )
    if duplicate_keys:
        raise RuntimeError(
            f"SEC-09.3: {duplicate_keys} doppelte Bestandsidentitäten gefunden. "
            "Vor der Migration fachlich prüfen und bereinigen; keine automatische Zusammenlegung."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_transaction_reverses"),
    ]

    operations = [
        migrations.RunPython(verify_stock_identity, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("item__isnull", False)),
                fields=("location", "item"),
                name="stock_unique_item_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("item_variant__isnull", False)),
                fields=("location", "item_variant"),
                name="stock_unique_variant_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.CheckConstraint(check=models.Q(("quantity__gte", 0)), name="stock_nonnegative_quantity"),
        ),
    ]
