# Generated by Django 2.2.19 on 2021-02-23 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='operations_manager',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Übungsleitung'),
        ),
    ]
