# Generated by Django 5.0.11 on 2025-06-04 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicebook', '0002_service_operations_manager'),
    ]

    operations = [
        # Add composite index for service queries (start date is most commonly used for ordering)
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS servicebook_service_start_idx ON servicebook_service (start);",
            reverse_sql="DROP INDEX IF EXISTS servicebook_service_start_idx;"
        ),
        
        # Add index for attendance queries by service
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS servicebook_attendance_service_idx ON servicebook_attendance (service_id);",
            reverse_sql="DROP INDEX IF EXISTS servicebook_attendance_service_idx;"
        ),
        
        # Add index for attendance queries by person
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS servicebook_attendance_person_idx ON servicebook_attendance (person_id);",
            reverse_sql="DROP INDEX IF EXISTS servicebook_attendance_person_idx;"
        ),
        
        # Add composite index for attendance state queries (used in statistics)
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS servicebook_attendance_state_idx ON servicebook_attendance (state, person_id);",
            reverse_sql="DROP INDEX IF EXISTS servicebook_attendance_state_idx;"
        ),
    ]
