# Generated by Django 5.0.14 on 2026-01-12 18:50

from django.db import migrations, models
from django.db.models import Count


def cleanup_duplicate_attendances(apps, schema_editor):
    """Remove duplicate attendance records, keeping the most recent one."""
    Attendance = apps.get_model('servicebook', 'Attendance')
    
    # Find all duplicate combinations of (person, service)
    duplicates = (
        Attendance.objects.values('person', 'service')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )
    
    deleted_count = 0
    for dup in duplicates:
        # Get all attendance records for this person/service combination
        records = Attendance.objects.filter(
            person_id=dup['person'],
            service_id=dup['service']
        ).order_by('-id')  # Most recent first
        
        # Keep the first (most recent) record, delete the rest
        records_to_delete = list(records[1:])
        for record in records_to_delete:
            record.delete()
            deleted_count += 1
    
    if deleted_count > 0:
        print(f"Cleaned up {deleted_count} duplicate attendance record(s)")


def reverse_cleanup(apps, schema_editor):
    """No reverse operation needed - duplicates were invalid data."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_emailmessage_emailrecipient_and_more'),
        ('servicebook', '0004_alter_attendance_id_alter_service_id'),
    ]

    operations = [
        # First, clean up existing duplicates
        migrations.RunPython(cleanup_duplicate_attendances, reverse_cleanup),
        # Then add the unique constraint
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('person', 'service')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['person', 'service'], name='servicebook_person__e116b2_idx'),
        ),
    ]
