# Generated by Django 5.0.9 on 2024-11-04 20:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20220923_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
