# Generated by Django 5.0.14 on 2025-09-18 18:17

import members.models.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, help_text='Zulässige Dateiformate: PDF, DOC, DOCX, JPG, PNG, GIF', null=True, upload_to=members.models.utils.get_attachment_file_path, verbose_name='Datei'),
        ),
    ]
