# Generated by Django 5.0.14 on 2026-04-03 19:53

import django.db.models.deletion
import members.models.email_message
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0018_emailmessage_emailrecipient_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    models.FileField(
                        upload_to=members.models.email_message.get_email_attachment_path, verbose_name="Datei"
                    ),
                ),
                ("original_filename", models.CharField(max_length=255, verbose_name="Originaldateiname")),
                ("file_size", models.PositiveIntegerField(default=0, verbose_name="Dateigröße (Bytes)")),
                ("content_type", models.CharField(blank=True, max_length=100, verbose_name="MIME-Typ")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                (
                    "email_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="members.emailmessage",
                        verbose_name="E-Mail-Nachricht",
                    ),
                ),
            ],
            options={
                "verbose_name": "E-Mail-Anhang",
                "verbose_name_plural": "E-Mail-Anhänge",
                "ordering": ["created_at"],
            },
        ),
    ]
