# Generated by Django 5.0.14 on 2026-04-29 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0020_add_gender_to_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Listenname")),
                ("description", models.TextField(blank=True, default="", verbose_name="Beschreibung")),
                ("color", models.CharField(default="#3B82F6", max_length=7, verbose_name="Farbe")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mitgliederliste",
                "verbose_name_plural": "Mitgliederlisten",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MemberListEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("checked", models.BooleanField(default=False, verbose_name="Abgehakt")),
                ("checked_at", models.DateTimeField(blank=True, null=True, verbose_name="Abgehakt am")),
                ("notes", models.CharField(blank=True, default="", max_length=500, verbose_name="Notiz")),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_entries",
                        to="members.member",
                        verbose_name="Mitglied",
                    ),
                ),
                (
                    "member_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="members.memberlist",
                        verbose_name="Liste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listeneintrag",
                "verbose_name_plural": "Listeneinträge",
                "ordering": ["member__lastname", "member__name"],
                "unique_together": {("member_list", "member")},
            },
        ),
    ]
