# Generated by Django 5.0.14 on 2026-05-01 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0001_initial"),
        ("members", "0021_add_member_list_and_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessage",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emails",
                to="departments.department",
                verbose_name="Abteilung",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="departments.department",
                verbose_name="Abteilung",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="departments",
            field=models.ManyToManyField(
                blank=True, related_name="members", to="departments.department", verbose_name="Abteilungen"
            ),
        ),
    ]
