# Generated by GitHub Copilot

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0001_initial"),
        ("members", "0022_emailmessage_department_group_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtype",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member_event_types",
                to="departments.department",
                verbose_name="Abteilung",
            ),
        ),
    ]
