# Generated by Django 5.0.14 on 2026-05-11 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0003_department_color"),
        ("members", "0023_eventtype_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComposeTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Vorlagenname")),
                ("subject", models.CharField(max_length=500, verbose_name="Betreff")),
                ("body_html", models.TextField(verbose_name="Nachricht (HTML)")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compose_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compose_templates",
                        to="departments.department",
                        verbose_name="Abteilung",
                    ),
                ),
            ],
            options={
                "verbose_name": "E-Mail-Vorlage",
                "verbose_name_plural": "E-Mail-Vorlagen",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["department", "is_active"], name="members_com_departm_c11497_idx")],
            },
        ),
    ]
