# Generated by Django 5.0.14 on 2026-05-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0024_add_compose_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessage",
            name="layout",
            field=models.CharField(
                choices=[
                    ("none", "Kein Layout"),
                    ("general", "Allgemein (lila)"),
                    ("important", "Wichtig (orange)"),
                    ("events", "Veranstaltung (grün)"),
                ],
                default="none",
                max_length=20,
                verbose_name="E-Mail-Layout",
            ),
        ),
        migrations.DeleteModel(
            name="ComposeTemplate",
        ),
    ]
