# Generated by Django 5.0.14 on 2026-09-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0025_add_layout_to_emailmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessage",
            name="recipient_members",
            field=models.ManyToManyField(
                blank=True, related_name="targeted_emails", to="members.member", verbose_name="Empfängermitglieder"
            ),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="recipient_type",
            field=models.CharField(
                choices=[
                    ("all", "Alle Mitglieder"),
                    ("group", "Gruppe"),
                    ("individual", "Einzelnes Mitglied"),
                    ("multiple", "Mehrere Mitglieder"),
                ],
                max_length=20,
                verbose_name="Empfängertyp",
            ),
        ),
    ]
