# Generated by Django 5.0.14 on 2026-10-04 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0003_department_color"),
        ("members", "0029_scope_legacy_member_lists"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberlist",
            name="legacy_resolved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Altlistenklärung abgeschlossen"),
        ),
        migrations.CreateModel(
            name="MemberListLegacyTarget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "department",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="departments.department"),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_targets",
                        to="members.memberlist",
                    ),
                ),
                (
                    "target",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_source_mapping",
                        to="members.memberlist",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="memberlistlegacytarget",
            constraint=models.UniqueConstraint(fields=("source", "department"), name="unique_legacy_list_target"),
        ),
    ]
