# Generated by Django 5.0.14 on 2026-10-05 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0030_memberlist_legacy_resolution"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={"permissions": [("export_member", "Kann Mitglieder exportieren")]},
        ),
    ]
