# Generated by Django 5.2.18 on 2026-10-08 11:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("departments", "0006_preserve_assignment_sources"),
        ("members", "0033_memberlist_organization_wide"),
        ("training", "0011_training_debrief"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("registered", "Angemeldet"),
                            ("waitlisted", "Warteliste"),
                            ("applied", "Beworben"),
                            ("assigned", "Zugeteilt"),
                            ("not_selected", "Nicht berücksichtigt"),
                            ("cancelled", "Abgemeldet"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "reason_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("krankheit", "Krankheit"),
                            ("schule_beruf", "Schule/Beruf"),
                            ("urlaub", "Urlaub"),
                            ("familie", "Familie"),
                            ("sonstiges", "Sonstiges"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                ("reason_note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("portal_parent", "Elternkonto"),
                            ("portal_member", "Mitgliedskonto"),
                            ("staff", "Betreuende"),
                        ],
                        max_length=14,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("state_changed_at", models.DateTimeField()),
                ("conflict", models.BooleanField(default=False)),
                ("conflict_reasons", models.JSONField(blank=True, default=list)),
                ("late", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="registrations", to="members.member"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="training.trainingsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meldung",
                "verbose_name_plural": "Meldungen",
            },
        ),
        migrations.CreateModel(
            name="RegistrationEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_state", models.CharField(blank=True, default="", max_length=12)),
                ("to_state", models.CharField(max_length=12)),
                ("at", models.DateTimeField()),
                ("via", models.CharField(max_length=14)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="participation.registration",
                    ),
                ),
            ],
            options={
                "ordering": ["at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SessionParticipation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "mode",
                    models.CharField(
                        choices=[("opt_out", "Abmeldung"), ("opt_in", "Anmeldung"), ("assignment", "Zuteilung")],
                        default="opt_out",
                        max_length=12,
                        verbose_name="Teilnahmemodus",
                    ),
                ),
                ("portal_visible", models.BooleanField(default=True, verbose_name="Im Portal sichtbar")),
                (
                    "public_note",
                    models.CharField(blank=True, default="", max_length=1000, verbose_name="Hinweis für Teilnehmende"),
                ),
                ("registration_opens_at", models.DateTimeField(blank=True, null=True)),
                ("registration_closes_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_closes_at", models.DateTimeField(blank=True, null=True)),
                ("max_participants", models.PositiveIntegerField(blank=True, null=True)),
                ("min_participants", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "waitlist_mode",
                    models.CharField(
                        choices=[("auto", "Automatisch nachrücken"), ("manual", "Manuell")],
                        default="auto",
                        max_length=8,
                    ),
                ),
                ("eligibility", models.JSONField(blank=True, default=dict)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participation",
                        to="training.trainingsession",
                        verbose_name="Dienst",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teilnahme-Konfiguration",
                "verbose_name_plural": "Teilnahme-Konfigurationen",
            },
        ),
        migrations.CreateModel(
            name="ParticipationDefaults",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "mode",
                    models.CharField(
                        choices=[("opt_out", "Abmeldung"), ("opt_in", "Anmeldung"), ("assignment", "Zuteilung")],
                        default="opt_out",
                        max_length=12,
                        verbose_name="Teilnahmemodus",
                    ),
                ),
                (
                    "registration_offset_h",
                    models.PositiveIntegerField(
                        default=48,
                        validators=[django.core.validators.MaxValueValidator(2160)],
                        verbose_name="Anmeldeschluss (Stunden vor Beginn)",
                    ),
                ),
                (
                    "cancellation_offset_h",
                    models.PositiveIntegerField(
                        default=2,
                        validators=[django.core.validators.MaxValueValidator(2160)],
                        verbose_name="Abmeldeschluss (Stunden vor Beginn)",
                    ),
                ),
                (
                    "waitlist_mode",
                    models.CharField(
                        choices=[("auto", "Automatisch nachrücken"), ("manual", "Manuell")],
                        default="auto",
                        max_length=8,
                        verbose_name="Warteliste",
                    ),
                ),
                (
                    "urgent_notice_h",
                    models.PositiveIntegerField(
                        default=24,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2160),
                        ],
                        verbose_name="Sofortmeldung bei Änderung (Stunden vor Beginn)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participation_defaults",
                        to="departments.department",
                        verbose_name="Abteilung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teilnahme-Standard",
                "verbose_name_plural": "Teilnahme-Standards",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("department__isnull", False)),
                        fields=("department",),
                        name="participation_defaults_dept_unique",
                    ),
                    models.UniqueConstraint(
                        models.Value(1),
                        condition=models.Q(("department__isnull", True)),
                        name="participation_defaults_org_unique",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(fields=["session", "state", "created_at"], name="registration_session_state"),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(fields=("session", "member"), name="registration_unique_member"),
        ),
    ]
