# Generated by Django 5.2.18 on 2026-10-09 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("participation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionparticipation",
            name="extra_places",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Weitere Plätze ohne Position"),
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=80, verbose_name="Bezeichnung")),
                ("min_count", models.PositiveSmallIntegerField(default=0, verbose_name="Mindestens")),
                ("max_count", models.PositiveSmallIntegerField(default=1, verbose_name="Plätze")),
                ("rule", models.JSONField(blank=True, default=dict)),
                ("position", models.PositiveSmallIntegerField(default=0, verbose_name="Reihenfolge")),
                (
                    "participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="participation.sessionparticipation",
                        verbose_name="Teilnahme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positionen",
                "ordering": ["position", "pk"],
            },
        ),
        migrations.AddField(
            model_name="registration",
            name="preferred_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="participation.slot",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registrations",
                to="participation.slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="slot",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_count__lte", models.F("max_count"))), name="slot_min_lte_max"
            ),
        ),
        migrations.AddConstraint(
            model_name="slot",
            constraint=models.CheckConstraint(condition=models.Q(("max_count__gte", 1)), name="slot_max_positive"),
        ),
    ]
