# Generated by Django 5.2.18 on 2026-10-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("participation", "0002_slots"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionparticipation",
            name="assignment_draft",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="sessionparticipation",
            name="assignment_keep_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sessionparticipation",
            name="assignment_published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
