# Generated by Django 5.2.18 on 2026-10-09 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0006_preserve_assignment_sources"),
        ("participation", "0003_assignment"),
        ("training", "0011_training_debrief"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffingTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                ("description", models.CharField(blank=True, default="", max_length=1000, verbose_name="Beschreibung")),
                ("body", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staffing_templates",
                        to="departments.department",
                        verbose_name="Abteilung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Besetzungsvorlage",
                "verbose_name_plural": "Besetzungsvorlagen",
                "ordering": ["name", "pk"],
            },
        ),
        migrations.AddField(
            model_name="sessionparticipation",
            name="template_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="participation.staffingtemplate",
            ),
        ),
        migrations.CreateModel(
            name="TemplateParticipation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staffing_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="participation.staffingtemplate",
                    ),
                ),
                (
                    "template",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participation",
                        to="training.trainingtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teilnahme der Übungsvorlage",
                "verbose_name_plural": "Teilnahme der Übungsvorlagen",
            },
        ),
    ]
