# Generated by Django 5.0.11 on 2025-05-27 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0013_alter_status_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('category', models.CharField(max_length=100, verbose_name='Kategorie')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('has_sizes', models.BooleanField(default=True, verbose_name='Hat Größen')),
                ('available_sizes', models.TextField(blank=True, help_text='Größen kommagetrennt eingeben, z.B.: XS,S,M,L,XL oder 98,104,110,116', verbose_name='Verfügbare Größen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bestellbarer Artikel',
                'verbose_name_plural': 'Bestellbare Artikel',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Status Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Status Code')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('color', models.CharField(default='#6c757d', help_text='Hex-Farbcode für die Anzeige', max_length=7, verbose_name='Farbe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
            ],
            options={
                'verbose_name': 'Bestellstatus',
                'verbose_name_plural': 'Bestellstatus',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Bestelldatum')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='Mitglied')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Bestellt von')),
            ],
            options={
                'verbose_name': 'Bestellung',
                'verbose_name_plural': 'Bestellungen',
                'ordering': ['-order_date'],
                'permissions': (('can_manage_orders', 'Kann Bestellungen verwalten'), ('can_change_order_status', 'Kann Bestellstatus ändern')),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Größe')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Anzahl')),
                ('received_date', models.DateTimeField(blank=True, null=True, verbose_name='Eingangsdatum')),
                ('delivered_date', models.DateTimeField(blank=True, null=True, verbose_name='Ausgabedatum')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderableitem', verbose_name='Artikel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Bestellung')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Bestellartikel',
                'verbose_name_plural': 'Bestellartikel',
            },
        ),
    ]
