# Generated by Django 5.0.11 on 2025-06-01 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0013_alter_status_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('template_type', models.CharField(choices=[('order_created', 'Bestellung erstellt'), ('status_update', 'Status geändert'), ('bulk_update', 'Massenänderung'), ('pending_reminder', 'Erinnerung'), ('daily_summary', 'Tägliche Zusammenfassung'), ('weekly_report', 'Wöchentlicher Bericht')], max_length=20, unique=True, verbose_name='Typ')),
                ('subject_template', models.CharField(max_length=255, verbose_name='Betreff-Vorlage')),
                ('html_template', models.TextField(verbose_name='HTML-Vorlage')),
                ('text_template', models.TextField(blank=True, verbose_name='Text-Vorlage')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'E-Mail-Vorlage',
                'verbose_name_plural': 'E-Mail-Vorlagen',
            },
        ),
        migrations.CreateModel(
            name='OrderableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('category', models.CharField(max_length=100, verbose_name='Kategorie')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('has_sizes', models.BooleanField(default=True, verbose_name='Hat Größen')),
                ('available_sizes', models.TextField(blank=True, help_text='Größen kommagetrennt eingeben, z.B.: XS,S,M,L,XL oder 98,104,110,116', verbose_name='Verfügbare Größen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bestellbarer Artikel',
                'verbose_name_plural': 'Bestellbare Artikel',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Status Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Status Code')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('color', models.CharField(default='#6c757d', help_text='Hex-Farbcode für die Anzeige', max_length=7, verbose_name='Farbe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
            ],
            options={
                'verbose_name': 'Bestellstatus',
                'verbose_name_plural': 'Bestellstatus',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_new_orders', models.BooleanField(default=True, verbose_name='Neue Bestellungen')),
                ('email_status_updates', models.BooleanField(default=True, verbose_name='Status-Änderungen')),
                ('email_bulk_updates', models.BooleanField(default=False, verbose_name='Massenänderungen')),
                ('email_pending_reminders', models.BooleanField(default=False, verbose_name='Erinnerungen für offene Artikel')),
                ('email_daily_summary', models.BooleanField(default=False, verbose_name='Tägliche Zusammenfassung')),
                ('email_weekly_report', models.BooleanField(default=False, verbose_name='Wöchentlicher Bericht')),
                ('reminder_frequency_days', models.PositiveIntegerField(default=7, verbose_name='Erinnerungs-Intervall (Tage)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benachrichtigungseinstellung',
                'verbose_name_plural': 'Benachrichtigungseinstellungen',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Bestelldatum')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='Mitglied')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Bestellt von')),
            ],
            options={
                'verbose_name': 'Bestellung',
                'verbose_name_plural': 'Bestellungen',
                'ordering': ['-order_date'],
                'permissions': (('can_manage_orders', 'Kann Bestellungen verwalten'), ('can_change_order_status', 'Kann Bestellstatus ändern')),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Größe')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Anzahl')),
                ('received_date', models.DateTimeField(blank=True, null=True, verbose_name='Eingangsdatum')),
                ('delivered_date', models.DateTimeField(blank=True, null=True, verbose_name='Ausgabedatum')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderableitem', verbose_name='Artikel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Bestellung')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Bestellartikel',
                'verbose_name_plural': 'Bestellartikel',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_created', 'Bestellung erstellt'), ('status_update', 'Status geändert'), ('bulk_update', 'Massenänderung'), ('pending_reminder', 'Erinnerung'), ('daily_summary', 'Tägliche Zusammenfassung'), ('weekly_report', 'Wöchentlicher Bericht'), ('order_summary', 'Bestellübersicht für Gerätewart')], max_length=20, verbose_name='Typ')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Empfänger')),
                ('subject', models.CharField(max_length=255, verbose_name='Betreff')),
                ('status', models.CharField(choices=[('sent', 'Gesendet'), ('failed', 'Fehlgeschlagen'), ('pending', 'Ausstehend')], default='pending', max_length=10, verbose_name='Status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gesendet am')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('additional_data', models.JSONField(blank=True, default=dict, verbose_name='Zusätzliche Daten')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Bestellung')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderitem', verbose_name='Bestellartikel')),
            ],
            options={
                'verbose_name': 'Benachrichtigungsprotokoll',
                'verbose_name_plural': 'Benachrichtigungsprotokolle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Geändert am')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Geändert von')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.orderitem', verbose_name='Bestellartikel')),
                ('from_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_history_from', to='orders.orderstatus', verbose_name='Von Status')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history_to', to='orders.orderstatus', verbose_name='Zu Status')),
            ],
            options={
                'verbose_name': 'Status-Änderung',
                'verbose_name_plural': 'Status-Änderungen',
                'ordering': ['-changed_at'],
            },
        ),
    ]
