# Generated by Django 5.0.11 on 2025-05-27 19:55

from django.db import migrations


def create_default_statuses(apps, schema_editor):
    """Erstelle Standard-Bestellstatus"""
    OrderStatus = apps.get_model('orders', 'OrderStatus')
    
    default_statuses = [
        {'name': 'Bestellt', 'code': 'ORDERED', 'color': '#ffc107', 'sort_order': 10},
        {'name': 'Eingegangen', 'code': 'RECEIVED', 'color': '#17a2b8', 'sort_order': 20},
        {'name': 'Ausgegeben', 'code': 'DELIVERED', 'color': '#28a745', 'sort_order': 30},
        {'name': 'Storniert', 'code': 'CANCELLED', 'color': '#dc3545', 'sort_order': 40},
    ]
    
    for status_data in default_statuses:
        OrderStatus.objects.get_or_create(
            code=status_data['code'],
            defaults=status_data
        )


def reverse_default_statuses(apps, schema_editor):
    """Entferne Standard-Bestellstatus"""
    OrderStatus = apps.get_model('orders', 'OrderStatus')
    default_codes = ['ORDERED', 'RECEIVED', 'DELIVERED', 'CANCELLED']
    OrderStatus.objects.filter(code__in=default_codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_statuses, reverse_default_statuses),
    ]
