# Generated by Django 5.0.11 on 2025-05-28 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20250527_1955'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Geändert am')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Geändert von')),
                ('from_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_history_from', to='orders.orderstatus', verbose_name='Von Status')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.orderitem', verbose_name='Bestellartikel')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history_to', to='orders.orderstatus', verbose_name='Zu Status')),
            ],
            options={
                'verbose_name': 'Status-Änderung',
                'verbose_name_plural': 'Status-Änderungen',
                'ordering': ['-changed_at'],
            },
        ),
    ]
