# Generated by Django 5.0.11 on 2025-05-28 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitemstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_created', 'Bestellung erstellt'), ('status_update', 'Status geändert'), ('bulk_update', 'Massenänderung'), ('pending_reminder', 'Erinnerung'), ('daily_summary', 'Tägliche Zusammenfassung'), ('weekly_report', 'Wöchentlicher Bericht')], max_length=20, verbose_name='Typ')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Empfänger')),
                ('subject', models.CharField(max_length=255, verbose_name='Betreff')),
                ('status', models.CharField(choices=[('sent', 'Gesendet'), ('failed', 'Fehlgeschlagen'), ('pending', 'Ausstehend')], default='pending', max_length=10, verbose_name='Status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gesendet am')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Bestellung')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderitem', verbose_name='Bestellartikel')),
            ],
            options={
                'verbose_name': 'Benachrichtigungsprotokoll',
                'verbose_name_plural': 'Benachrichtigungsprotokolle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_new_orders', models.BooleanField(default=True, verbose_name='Neue Bestellungen')),
                ('email_status_updates', models.BooleanField(default=True, verbose_name='Status-Änderungen')),
                ('email_bulk_updates', models.BooleanField(default=False, verbose_name='Massenänderungen')),
                ('email_pending_reminders', models.BooleanField(default=False, verbose_name='Erinnerungen für offene Artikel')),
                ('email_daily_summary', models.BooleanField(default=False, verbose_name='Tägliche Zusammenfassung')),
                ('email_weekly_report', models.BooleanField(default=False, verbose_name='Wöchentlicher Bericht')),
                ('reminder_frequency_days', models.PositiveIntegerField(default=7, verbose_name='Erinnerungs-Intervall (Tage)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benachrichtigungseinstellung',
                'verbose_name_plural': 'Benachrichtigungseinstellungen',
            },
        ),
    ]
