# Generated by Django 5.0.11 on 2025-05-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_notificationlog_notificationpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('template_type', models.CharField(choices=[('order_created', 'Bestellung erstellt'), ('status_update', 'Status geändert'), ('bulk_update', 'Massenänderung'), ('pending_reminder', 'Erinnerung'), ('daily_summary', 'Tägliche Zusammenfassung'), ('weekly_report', 'Wöchentlicher Bericht')], max_length=20, unique=True, verbose_name='Typ')),
                ('subject_template', models.CharField(max_length=255, verbose_name='Betreff-Vorlage')),
                ('html_template', models.TextField(verbose_name='HTML-Vorlage')),
                ('text_template', models.TextField(blank=True, verbose_name='Text-Vorlage')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'E-Mail-Vorlage',
                'verbose_name_plural': 'E-Mail-Vorlagen',
            },
        ),
    ]
