# Generated by Django 5.0.11 on 2025-06-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Zusätzliche Daten'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('order_created', 'Bestellung erstellt'), ('status_update', 'Status geändert'), ('bulk_update', 'Massenänderung'), ('pending_reminder', 'Erinnerung'), ('daily_summary', 'Tägliche Zusammenfassung'), ('weekly_report', 'Wöchentlicher Bericht'), ('order_summary', 'Bestellübersicht für Gerätewart')], max_length=20, verbose_name='Typ'),
        ),
    ]
