# Generated by Django 5.0.14 on 2026-04-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_email_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', help_text='Bevorzugter Farbmodus (Hell, Dunkel, System)', max_length=10, verbose_name='Theme-Modus'),
        ),
    ]
