# Generated by Django 5.0.14 on 2026-05-02 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0002_replace_role_field_with_groups_m2m"),
        ("users", "0005_customuser_theme_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="favorite_department",
            field=models.ForeignKey(
                blank=True,
                help_text="Wird beim Login als Standard-Abteilung gewählt",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favorite_users",
                to="departments.department",
                verbose_name="Bevorzugte Abteilung",
            ),
        ),
    ]
