# Generated by Django 5.0.14 on 2026-05-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_add_favorite_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="auth_source",
            field=models.CharField(
                choices=[("local", "Lokal"), ("ldap", "LDAP"), ("oidc", "OIDC")],
                default="local",
                help_text="Gibt an, ob der Benutzer lokal oder über ein externes System (LDAP/OIDC) verwaltet wird.",
                max_length=10,
                verbose_name="Authentifizierungsquelle",
            ),
        ),
    ]
