# Generated by Django 5.2.18 on 2026-10-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_passkeys"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="account_kind",
            field=models.CharField(
                choices=[("staff", "Verwaltung"), ("portal", "Portal (Eltern/Mitglied)")],
                default="staff",
                help_text="Portalkonten (Eltern, Mitglieder) erreichen nur Portalfunktionen und erhalten nie Rollen.",
                max_length=10,
                verbose_name="Kontoart",
            ),
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("account_kind", "staff"),
                    models.Q(("auth_source", "local"), ("is_staff", False), ("is_superuser", False)),
                    _connector="OR",
                ),
                name="portal_account_is_plain_local",
            ),
        ),
    ]
