# Generated by Django 2.1.3 on 2019-02-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joined',
            field=models.DateField(blank=True, null=True, verbose_name='Eingetreten'),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Geburtstag'),
        ),
    ]
