# Generated by Django 3.2.6 on 2022-06-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20191031_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='canSwimm',
            field=models.BooleanField(default=False, verbose_name='Kann schwimmen:'),
        ),
    ]
